spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bear
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123456

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally
